### ISSUE TITLE
The Plex local data folder could not be determined

### ISSUE THREAD

**Issue by kravena** [TechieGuy12/PlexServerAutoUpdater#1]
When running psupdate.exe using RUN AS ADMINISTRATOR, I get the error "The Plex local data folder could not be determined".

Most likely this is due to me moving the PLEX MEDIA SERVER directory to another drive using a JUNCTION. So it looks like the PLEX MEDIA SERVER data folder is on C: when it's actually on D:, for example : 

c:\users\<USER>\AppData\Local\Plex Media Server is a JUNCTION to d:\Plex Media Server

This is done due using a 480gb SSD as the C drive and my Plex data directory is 100gb, use of a JUNCTION makes the configuration of Plex much simpler without altering the settings or registry.

**Comment by TechieGuy12** [comment]
Can you verify that the following registry value exists for the user that is running the Plex Service:

Key: `HKEY_CURRENT_USER\SOFTWARE\Plex, Inc.\Plex Media Server`
Value: `LocalAppDataPath`

The error message is reported when the above key can't be read from the registry for the user that is running the Plex Service.

**Comment by kravena** [comment]
That setting does not exist under that key and checking an old backup of my Plex registry settings, I have never had it.

**Comment by TechieGuy12** [comment]
I have updated to version 0.1.2 which defaults to the local application data folder of the user if the LocalAppDataPath value is not found in the registry.

**Comment by kravena** [comment]
0.1.2 installed, which now runs perfectly. Waiting for next PMS Plex Pass update to verify.

Thank you.
