### ISSUE TITLE
False positive from Windows Defender?

### ISSUE THREAD

**Issue by balogg** [TechieGuy12/PlexServerAutoUpdater#11]
Just thought i'd quickly let you know that when i downloaded the psupdate.zip file, via Chrome, Windows Defender blocked it.

Trojan:Win32/Fuerboox.A!cl

I've attached the screenshot from Defender.

![psupdate image](https://user-images.githubusercontent.com/8469851/32091331-61c851aa-bb3f-11e7-9c94-f68adf690afd.png)

**Comment by TechieGuy12** [comment]
Thanks.  I am getting it too.  The file is safe, so I will have to find out how to resolve this issue.

**Comment by TechieGuy12** [comment]
I submitted a request to Microsoft regarding the issue.  I was able to download the zip file today without any issue.  Do you still see the Defender warning when you download the zip file?

**Comment by blackholeearth** [comment]
virustotal result. https://www.virustotal.com/#/file/a6b1a5616f8067f95e17ee74907ccfbdc41f4cc46fa83f8d71ac8d0887a37679/detection ,

please scan it for yourself.  20 to 1. windowsDEfender is wrong

**Comment by TechieGuy12** [comment]
Can you try again?  I have seen the error before, but I am not getting the error now.
