### ISSUE TITLE
"Automatically Download Updates" no longer an option

### ISSUE THREAD

**Issue by vanatom** [TechieGuy12/PlexServerAutoUpdater#12]
I realize this is a Plex thing, and not an actual "issue" with AutoUpdater... but, when following your instructions on how to configure the Plex server to automatically download updates, I've noticed that the only options are "Ask me" and to update "Automatically during scheduled maintenance" (see screenshot).

This may be a new change in the Plex Pass beta, but that means it will eventually be in the Public channel. How can we configure Plex to download updates without installing them if that's no longer an option? I've checked the Scheduled Tasks section of Plex server settings as well, just in case, and unfortunately there's no additional download/update options there either.

![image](https://user-images.githubusercontent.com/1059469/32279270-a243bd70-beee-11e7-9e44-5dca9e78ea5e.png)

**Comment by TechieGuy12** [comment]
That is a good question.  I am looking into adding the download automatically option into the updater utility.  That should solve the problem of having to manually download the update.

**Comment by vanatom** [comment]
Awesome! Thanks so much for all your work on this.

We have a client who's payed us way too much money to build and manage his Plex server. Suffice to say, he cannot handle the process of manually updating Plex when running as a Windows service and we... have better things to do. lol So having a scheduled auto-updater saves him 15 minutes of billable time a week and saves us a 30 minute phone call having to listen to him brag about his iPhone X or his WiFi-enabled meat-dehydrator. -_-

Seriously... thank you for making this and saving us the hassle. I'll be looking out for an updated version! In the meantime, we've tried to structure the Plex server's maintenance window and the scheduled task so that if Plex tries to auto-update and breaks the Windows service, your AutoUpdater will re-start the service properly. So far, I think it's working since we haven't gotten an angry morning call saying Plex is down. :)

**Comment by Eds1989** [comment]
Is it perhaps feasible to simply download the latest version of the installer from the Plex website during the update process? This could be copied into the directory Plex would normally download the installer to, and can be run from there as normal?

**Comment by TechieGuy12** [comment]
@Eds1989 It is very feasible and not difficult to do. Once I have some time I will implement this feature.

**Comment by TechieGuy12** [comment]
I have added the automatic download functionality to the updater.  [Release 0.1.6.0](https://github.com/TechieGuy12/PlexServerAutoUpdater/releases/tag/v0.1.6.0) will now download the latest version of Plex before running an update.
