### ISSUE TITLE
ERROR: Object reference not set to an instance of an object. in Version 1.6.0

### ISSUE THREAD

**Issue by superpatty** [TechieGuy12/PlexServerAutoUpdater#13]
Just downloaded the updater v1.6.0 and i always get the error:
ERROR: Object reference not set to an instance of an object.

I'm attempting to update from 1.10.1.4602 -> 1.12.0.4829 of Plex

I downloaded 1.5.4 and it worked fine with the same update to Plex

START: Stopping the Plex service.
END: Stopping the Plex service.
START: Stopping the Plex Server processes.
END: Stopping the Plex Server processes.
START: Running update: C:\Users\satyr\AppData\Local\Plex Media Server\Updates\1.12.0.4829-6de959918\packages\Plex-Media-Server-1.12.0.4829-6de959918.exe.
END: Running update.
START: Stopping the Plex Server processes.
END: Stopping the Plex Server processes.
START: Restarting the Plex service.
END: Restarting the Plex service.

**Comment by TechieGuy12** [comment]
The next time there is a Plex update can you try running 0.1.6.0 again? If the error still occurs can you send me the %temp%\plex-updater.txt file?

**Comment by c17r** [comment]
I got the same error just now.  Here's the file

[plex-updater.txt](https://github.com/TechieGuy12/PlexServerAutoUpdater/files/1839420/plex-updater.txt)

**Comment by TechieGuy12** [comment]
Can you try version [0.1.6.1](https://github.com/TechieGuy12/PlexServerAutoUpdater/releases/tag/v0.1.6.1)?

**Comment by c17r** [comment]
Unfortunately I ran the plex update using 0.1.5.4 so I'll have to wait for another plex release.  I do have 0.16.1 installed now though

**Comment by aaronchi** [comment]
I can't even get 0.1.6.1 to run. Gives me an error with parameter path1 being null.
[plex-updater.txt](https://github.com/TechieGuy12/PlexServerAutoUpdater/files/1887930/plex-updater.txt)

**Comment by TechieGuy12** [comment]
It seems you have a different issue. The updater is having issues getting the Plex local application path  from the registry for the user running the Plex service.  The Plex local application path is retrieved from the registry at:

HKEY_CURRENT_USER\SOFTWARE\Plex, Inc.\Plex Media Server\LocalAppDataPath

**Comment by superpatty** [comment]
It looks like the latest update (0.1.6.2) is working
https://imgur.com/a/rSTRupB

Thanks!

Patrick
