### ISSUE TITLE
Plex no longer has an “Automatically download updates” option

### ISSUE THREAD

**Issue by robross0606** [TechieGuy12/PlexServerAutoUpdater#18]
The server configuration options on the General tab no longer have “Automatically download updates” as an option.  The only available options are "Ask me" and "Automatically during scheduled maintenance".  It is unclear what happens if this option is selected but the Plex Auto Update service is not set to Automatic or, even worse, disabled.

**Comment by TechieGuy12** [comment]
I am not sure about those options as they are really outside the control of this application.
