### ISSUE TITLE
Error: "Some or all identity references could not be translated"

### ISSUE THREAD

**Issue by seanvree** [TechieGuy12/PlexServerAutoUpdater#2]
Hey man! Thanks for this! Awesome!

I tried to run the .exe but I get the following error:

"Some or all identity references could not be translated"

I tried running from a CMD prompt as well, no dice. 

My system:

Windows 10 Enterprise

Plex running as a service

Ran with admin privileges

Any ideas?

**Comment by TechieGuy12** [comment]
I'll have to look into the issue. The issue appears to come from a principal that can't be mapped to a known identity on your computer. I'll see if I can code around it.

**Comment by seanvree** [comment]
thanks @TechieGuy12 ! Let me know if I can help

**Comment by TechieGuy12** [comment]
Version 0.1.3.1 is in the development branch. Can you try out that version to see if the problem still exists?

**Comment by seanvree** [comment]
Okay, so If I just double lick on the .exe, I don't get a prompt or anything, doesn't seem to stop the plex service. So how do I know it worked since there is no update available?  

I then ran from a admin cmd prompt and I got the error:  "no mapping between account names and security IDs was done"

LMK.

**Comment by TechieGuy12** [comment]
Hmm.  Can you try doing he following:

1. Open gpedit.msc as an administrator.
2. Click **Computer Configuration**->**Windows Settings**->**Security Settings**->**Local Policies**->**User Rights Assignment**.
3. On the right, double-click the **Allow log on locally** option.
4. Ensure that at least the **Administrators** and **Users** groups are in the list. If not, add them using the **Add User or Group** button.
5. Restart your machine.

**Comment by seanvree** [comment]
Yeah, no changes needed to be made there.

If you'd like, I can let you RDC into my machine so you can take a look?  LMK.  seanvree@hotmail.com.

**Comment by TechieGuy12** [comment]
Hi,

RDC into your machine is an option.  I have updated the development branch with another change in code to lookup the user SID.  Can you give it a try?

**Comment by seanvree** [comment]
okay, so if I run the .exe by just doub-clicking it or right clicking and "run as admin" I didn't get an error or any message all, so may have worked? How do I know if it ran?

I also tried opening a CMD prompt and CD to it's directory then typing the.exe, and when I do that I get "The SID for the user was not specified"

**Comment by TechieGuy12** [comment]
Have you logged into the machine using the account that is running the Plex service? The issue seems to be that the updater can't find the SID associated with the Plex service account.

**Comment by seanvree** [comment]
Well, the PLEX service in my case runs as a Windows Service. No user needs to be logged on.  However, I have tried the administrator account, as well as another account that has admin privileges.

**Comment by TechieGuy12** [comment]
What user does the Plex Service run under?  There should be an log in account associated with the Plex service.  If so, try logging in with that account once and then log off again.

**Comment by seanvree** [comment]
it's the "Local System" account, like all the other windows services. Everything I've set up on this system is under the admin account which is what I use to manage the system.

**Comment by TechieGuy12** [comment]
Thanks, knowing that the service runs under the Local System account is helpful. I will provide a new update that will hopefully work with the Local System account.

**Comment by seanvree** [comment]
no prob @TechieGuy12 , like I said, if you'd like to RDC into my server, I can do that.  Let me know.

**Comment by TechieGuy12** [comment]
I have updated the Development branch to work with the Local System account. I had to ensure my LocalAppDataPath registry key for Plex was set (if you changed it then it would be set under the Local System account).

**Comment by seanvree** [comment]
BOOM!

**Comment by TechieGuy12** [comment]
I take it the update worked?  If so, I will update the master version and close the issue.

**Comment by seanvree** [comment]
Yes! I mean, it's hard to say if it will work when an update is released, but the app runs! May want to wait until a PLEX update comes out to see how it interacts with actually updating the service. Up to you.

**Comment by TechieGuy12** [comment]
I will close the issue because it refers to the identity mapping issue, which appears to be resolved. If you do get an error while upgrading, just open a new issue.
