### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by abarber229** [TechieGuy12/PlexServerAutoUpdater#23]
Not an issue, but just a quick question since I didn't see an email. If I run the the updater as a scheduled task, what happens if there isn't a new update when the task runs? Does it still go through the motions of stopping all services and restarting them, or is there a check version before downloading? Or does it download the update again and re-install the update?

**Comment by TechieGuy12** [comment]
It won't stop any of the services or Plex processes if an update is not available. When the silent update is run, the following will happen:

1. It will contact Plex to get the latest version, and if one exists it will check to see if it was already downloaded. If it was downloaded, then it will verify the checksum to ensure it matches.
2. If the latest version that was downloaded, or was downloaded previously is newer, then the update will happen - all services/processes are stopped, the update happens, and then Plex is restarted.
3. If the latest version matches the currently installed version, then nothing happens.
