### ISSUE TITLE
PSAU doesn't pull latest update

### ISSUE THREAD

**Issue by seanvree** [TechieGuy12/PlexServerAutoUpdater#4]
So a PLEX server update was released today, but the .exe didn't find it.  Is it pulling from PlexPass?

See screen shot. 

![img_20160818_111552](https://cloud.githubusercontent.com/assets/8906637/17789414/f6a4dcbc-6546-11e6-9b00-f9149df6fc60.jpg)

**Comment by TechieGuy12** [comment]
The app doesn't pull the latest update. Have Plex download the updates and then run the update application to install the update.
