### ISSUE TITLE
"An Error Occurred while sending the request"

### ISSUE THREAD

**Issue by theg1nger** [TechieGuy12/PlexServerAutoUpdater#42]
Plex install folder: C:\Program Files (x86)\Plex\Plex Media Server.
Plex local data folder: C:\Users\XXXX\AppData\Local.
Updates folder: C:\Users\XXXX\AppData\Local\Plex Media Server\Updates.
Update channel: Plex Pass.
Verify the updates folder is specified.
Verify the updates folder, C:\Users\XXXX\AppData\Local\Plex Media Server\Updates exists.
Getting ready to download the latest package.
Checking for the latest version from Plex.
The update channel is set for Plex Pass.
**Could not get Plex package information. Message: An error occurred while sending the request..
Could not get the latest version information from Plex.**
The latest Windows version has not been specified.
The latest available installation could not be downloaded.
Current version: 1.20.2.3370.
Lastest version: 1.20.2.3370.

Plex Pass has a new update 1.20.2.3402  but ps update is not able to find it. 
Using 0.2.0.0 Beta 1
W10 20H2 (19042.546)

**Comment by theg1nger** [comment]
Rolling back to 0.1.9.0 seems to resolve the issue. 0.2.0.0 b1 was working fine until the last Plex Server update. Wonder what changed that broke it.

**Comment by TechieGuy12** [comment]
I can reproduce the issue on my server. Let me have a look and see what the issue is.

**Comment by TechieGuy12** [comment]
On the next update, try this release: [0.2.0.0-beta.2](https://github.com/TechieGuy12/PlexServerAutoUpdater/releases/tag/0.2.0.0-beta.2).

**Comment by AnthonyBe** [comment]
Interesting. I started seeing this _exact_ same issue and error using psupdate 0.1.9.0 on my Windows Server 2012 R2 server with the 1.20.2.3402 PMS update.

I just updated to psupdate 0.2.0.0 beta 2 and it successfully updated.

Thanks @TechieGuy12 !

**Comment by TechieGuy12** [comment]
The issue  will probably appear with 0.1.9.0. I will need to update that one too.

**Comment by TechieGuy12** [comment]
Release [0.1.9.1](https://github.com/TechieGuy12/PlexServerAutoUpdater/releases/tag/0.1.9.1) contains the fix for the release version.

**Comment by AnthonyBe** [comment]
I noticed in that commit of LatestAvailableVersion.cs what looks to be hardcoding of the TLS protocol in line 358 to TLS 1.2?

`System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;`

If I'm correct, while that will work, it prevents the use of TLS 1.3 where available which is faster and more secure. Better to let the OS auto-determine the security protocol to use (https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls)

If I've misunderstood that bit of code, apologies, and I'll crawl back into my box! :)

**Comment by TechieGuy12** [comment]
You are correct.  I have specifically set the protocol to 1.2.  With version 0.1.9.x, the targetted version of .Net Framework is 4.5. This means that I can't use the protocol specified by the OS as it isn't available in .Net 4.5. In that case, I specifically set it to TLS 1.2. I didn't want to update the .Net version to 4.7+ to keep the compatibility with all 0.1.9.x versions.

With version 0.2.0.0, I have changed the targetted .Net Framework version to 4.7.2, which now allows me to use the OS-specified protocol. I have since updated 0.2.0.0 to remove the hard-coded TLS 1.2, but have yet to compile the version. I am waiting to first test it on my server, but feel free to compile and run the latest code in the Restructure branch.

**Comment by theg1nger** [comment]
@TechieGuy12 Yup. Looks like that fixed it. 0.2.0.0-beta.2

```
2020-10-07 18:50:46 Current version: 1.20.2.3402.
2020-10-07 18:50:46 Latest version: 1.20.3.3401.
```
Didn't have to download the update manually via myplex. Updated successfully. Thanks!
