### ISSUE TITLE
Plex Updater Error - The Plex data folder could not be found

### ISSUE THREAD

**Issue by Alternetwork** [TechieGuy12/PlexServerAutoUpdater#48]
![psupdate error](https://user-images.githubusercontent.com/79710387/109320670-1a849c00-7805-11eb-9c2b-e18bfdcc29e7.jpg)

No clue, was working fine on a windows server essentials 2016 plex server, then on a new install of a win 10 pro plex server. Works fine on all my other servers. None of them have the plex data folder in the default location. but most pre-date when plex removed that from SETTINGS > GENERAL  options.

**Comment by TechieGuy12** [comment]
The application gets the data folder location from **HKEY_CURRENT_USER\SOFTWARE\Plex, Inc.\Plex Media Server**. The value is **LocalAppDataPath**.
