### ISSUE TITLE
Plex Pass updates

### ISSUE THREAD

**Issue by v3000** [TechieGuy12/PlexServerAutoUpdater#5]
Update shows only free updates.

**Comment by Vhex** [comment]
It works for me.  You have Plex set to automatically download updates?

**Comment by TechieGuy12** [comment]
Hi v3000,

It will show the updates that have been downloaded by Plex (my application doesn't do this as Plex handles the downloads).

As Vhex mentioned, do you have Plex setup to automatically download updates? If you do, then he PlexServerAutoUpdater should detect the updates and install them for you.

I have a Plex Pass and I have no issues installing Plex Pass-only updates.

If you are still having issues, then let me know the details and I will look into it for you.
