### ISSUE TITLE
Invalid class?

### ISSUE THREAD

**Issue by PixelDew121** [TechieGuy12/PlexServerAutoUpdater#50]
I haven't used my server in a while and decided to get back to Plex but when I tried to launch the updater it just gives me an error saying "Invalid Class".

I thought maybe it was because it's received an update since so I got the latest version and it still says the same, I'm not very good with tech so I have no idea what it means or what happened since the last time I used it, help would be much appreciated!

**Comment by sbeaudoin** [comment]
I was thinking to use this, but this bug has no update for more than a year and not commit since a long time.  I think this project is dead.  Did you solve your issue?

**Comment by TechieGuy12** [comment]
The project isn't dead, bu in haven't provided and update in some time. I still use this to update Plex today.

Do you also get this error?

If so, can someone outline the steps they use to get the error?

**Comment by sbeaudoin** [comment]
I don't have this error. I was curious to why this user did not have any answer for more than a year.
