### ISSUE TITLE
PMS x64 Compatability

### ISSUE THREAD

**Issue by TempestWales** [TechieGuy12/PlexServerAutoUpdater#52]
Plex is releasing a 64bit Server, I've installed the preview, but as the x64 bit Version is higher than the 32bit, I think the Updater will need to detect the 64bit version and looks for updates for that channel.

I dont think however Plex have released any update jsons (ie  https://plex.tv/api/downloads/1.json)

Current version: 1.28.1.5985.
Latest version: 1.27.2.5929.

https://forums.plex.tv/t/preview-plex-media-server-for-windows-64-bit-version/801401

**Comment by TechieGuy12** [comment]
It is something that I will be looking at implementing for sure.

**Comment by TechieGuy12** [comment]
The pre-release version [0.2.1.0-beta.3](https://github.com/TechieGuy12/PlexServerAutoUpdater/releases/tag/0.2.1.0-beta.3) contains the support for the 64-bit version of the server for Windows. It should automatically detect if the install is either 32-bit or 64-bit version and download the latest version.

**Note:** You can't use this version to move from 32-bit to 64-bit. That will need to be done manually by downloading the 64-bit installation of the server, and then having it uninstall the 32-bit version. Once that is done, PlexServerAutoUpdater will then run the updates for the 64-bit version.

**Comment by tiagocoelho2** [comment]
There is the psupdate.exe.config file. Is it necessary to change to x64 installer parameters?

**Comment by TempestWales** [comment]
As a side note, Im getting a Dot Net 4.8 Requirement.

![image](https://user-images.githubusercontent.com/10633668/194358525-6f58ef31-836b-4501-9e1f-8ed8fe64040e.png)

**Comment by TechieGuy12** [comment]
> As a side note, Im getting a Dot Net 4.8 Requirement.
> 
> ![image](https://user-images.githubusercontent.com/10633668/194358525-6f58ef31-836b-4501-9e1f-8ed8fe64040e.png)

As this time, the updater requires .Net Framework 4.8. Will be looking at moving to .NET 6.0.

**Comment by TechieGuy12** [comment]
It was necessary to change the installation parameters for the 64-bit version. [0.2.1.0-beta.4](https://github.com/TechieGuy12/PlexServerAutoUpdater/releases/tag/0.2.1.0-beta.4) has the correct parameters.

**Comment by tiagocoelho2** [comment]
Thank you for your support. : )
