### ISSUE TITLE
Plex Service not Installed

### ISSUE THREAD

**Issue by sbeaudoin** [TechieGuy12/PlexServerAutoUpdater#59]
What I did
------------
- Copied version 0.2.1.1 in C:\Program Files\Plex Auto Updater.
- Plex server run as a service and ONLY as a service with NSSM as "Plex Media Server".
- Plex server is installed in "C:\Program Files\Plex\Plex Media Server\Plex Media Server.exe".
- The service "Plex Media Server" is running and the web UI is available.
- Changed "PlexServiceName" of "psupdate.exe.config" to "Plex Media Server".
- First run strangely gives an error concerning the bluetooth stack being absent, did not occur on the following executions.
- Launched "psupdate.exe" as an administrator.

What occured
----------------
- Popup titled "Plex Updater Error" with the text "The Plex Service is not Installed".

What was expected
----------------------
- A windows with an "upgrade" button.

**Comment by sbeaudoin** [comment]
Looking at the code, I see the parameter name is configusing.  It is not the service name, but the display name of the installation package.

As my installation package was "Plex Media Server 1.29.1.6316 (x64)", I changed the "PlexServiceName" to that and it does not change nothing.

Looked at the registry key "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{688e1d8f-188e-49cd-83ca-2669a7e3f8cc}_is1", and the display name is correctly "Plex Media Server 1.29.1.6316 (x64)".

**Comment by TechieGuy12** [comment]
For the service name specified in the config file, you will need to use the value that is displayed in the service properties:

![image](https://user-images.githubusercontent.com/16374974/202339262-7aee2e7b-9919-4a35-a37d-db0b729afabf.png)

**Comment by sbeaudoin** [comment]
Oh!  Yes, it did work.  I suggest to make a service selection list available.  This would show all services installed who point to nssm,exe.  This would be easier than change a config file without remembering there is a display name and a service name and use the wrong one, as I did.

**Comment by TechieGuy12** [comment]
Plex can be installed as a service without using NSSM so I would need to list all services to ensure I won't miss any. This also wouldn't work when running the updater from a command line. 

Instead, I'll update the code so either the service name or display name can be used to identify the service.
