### ISSUE TITLE
Error: object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Okyd** [TechieGuy12/PlexServerAutoUpdater#6]
When Launching psupdate.exe I get the error:
object reference not set to an instance of an object.

on: Windows Server 2016

**Comment by TechieGuy12** [comment]
What version of PlexServerAutoUpdater are you using?  Are you logged in with an admin or standard user account, or System account?

**Comment by Okyd** [comment]
Can be resolved - Installed old (3.5)  .NET feature and rebooted, and it is now running.
